# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: mhamin10.github.io
baseurl:
title: Mohamed H. Amin
author: Mohamed H. Amin
description: Personal Site
avatar: picture.jpg
email: mh.amin@live.com
github: mhamin10 # username
twitter: mhamin10
linkedin: mhamin
#stackoverflow:   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus:
#google_analytics:


# needed for travis-ci build
exclude: [vendor]
