title: Mohamed Amin | mamindev
author: Mohamed Amin
email: mh.amin@live.com
description: > # this means to ignore newlines until "twitter_username:"
  Hello! I am Mohamed Amin. I design and build solutions that help companies move and process
  to drive business value. 

# social links
twitter_username: mamindev
github_username:  mamindev
#rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: mamindev
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - projects.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
